name: Check code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build with Gradle
        run: gradle clean test

      - name: Archive Rest Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: GradleReports/emailable-report.html